# Generated by Django 4.2.18 on 2025-01-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('CSE', 'CSE'), ('TE', 'TE'), ('ME', 'ME')], default='ICT', max_length=50)),
            ],
        ),
    ]
